version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    ports:
      - '3000:3000'
    networks:
      - btc-network
    depends_on:
      - db

  db:
    build:
      context: ./postgresdb
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: application
    ports:
      - '5432:5432'
    networks:
      - btc-network

volumes:
  postgres-data:

networks:
  btc-network:
    driver: bridge